### ISSUE TITLE
Office hours?

### ISSUE THREAD

**Issue by keeth** [brandonshin/slackbot-workout#17]
How do you make it 'sleep' during off hours?  Or does everyone need to set their status to away?

**Comment by craig-davis** [comment]
It does appear to ignore `/away` users, but it may still send a `@channel` group exercise in the wee hours of the morning. You could certainly start and stop with a cron, but office hours would be a great addition.

**Comment by slinlee** [comment]
I added rudimentary support for this here:
https://github.com/brandonshin/slackbot-workout/pull/20

**Comment by craig-davis** [comment]
Nice work! Thanks!

**Comment by brandonshin** [comment]
awesome! thanks @slinlee  @craig-davis I'll check/test it and pull it in later today 👌

**Comment by brandonshin** [comment]
thanks @keeth for the comment as well.

**Comment by slinlee** [comment]
@brandonshin yeah, let me know if you have any comments or suggestions for cleaning it up. It was a pretty quick add :)

We're having a lot of fun with this at the office so far.

**Comment by slinlee** [comment]
Just updated the PR to include the config toggle for turning the officehours feature on and off. Check it out.
