### ISSUE TITLE
Environmental variables 

### ISSUE THREAD

**Issue by traceyvanp** [brandonshin/slackbot-workout#24]
I'm having troubles installing the environmental variables using the $ export command within the terminal. It doesn't change anything within the python files. 

How can I update the "USER_TOKEN_STRING" and the "URL_TOKEN_STRING" within the files?

Within slackbotExercise.py, I set the tokens as such:
USER_TOKEN_STRING =  os.environ['xoxp-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx']
URL_TOKEN_STRING =  os.environ['iFB9xxxxxxxxxxxxxxxxxxx']

When I run $ python slackbotExercise.py I get a key error on the USER_TOKEN_STRING.

**Comment by dhaubert** [comment]
you should change like this
USER_TOKEN_STRING = "xoxp-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx"
URL_TOKEN_STRING = "iFB9xxxxxxxxxxxxxxxxxxx"

At this case, you have changed the array key instead of the value.

You must change the User.py file to in the same way.

**Comment by traceyvanp** [comment]
That solved that problem! Thank you!
